### ISSUE TITLE
Enhancing the ui of dashboard page 

### ISSUE THREAD

**Issue by AayushhGoyal** [Devmangrani/JobSewa#100]
## Issue
The total appliead and saved job button has so much hit and are really big which is degrading the overall ambience of the website 

![image](https://github.com/user-attachments/assets/19cbfda7-349c-4eca-abf5-2b57fb09215a)
![image](https://github.com/user-attachments/assets/68ff3ee2-ca4e-443f-9d96-e935f4cf0f0c)

**Comment by AayushhGoyal** [comment]
please assign me on this one @Devmangrani

**Comment by Devmangrani** [comment]
Sure, @AayushhGoyal  
I’ll assign it to you. Looking forward to seeing your contribution!
