### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AayushhGoyal** [Devmangrani/JobSewa#103]
**Describe the bug**
The arrow symbol should be on same line as of jobs

## Screenshots
![image](https://github.com/user-attachments/assets/ea4713cc-2e35-4d76-9bc3-51447d7425b3)

**Comment by AayushhGoyal** [comment]
@Devmangrani assign me

**Comment by Devmangrani** [comment]
@AayushhGoyal  Assigned to you! Thanks for addressing this.

**Comment by AayushhGoyal** [comment]
@Devmangrani bhai i have fixed it can merge

**Comment by Devmangrani** [comment]
I’ve merged it! Thanks for the fix, and happy Diwali to you  🎉😊
