### ISSUE TITLE
"Objects are not Valid as a Child" in JobCard component

### ISSUE THREAD

**Issue by ubaidrmn** [Devmangrani/JobSewa#12]
This error appears when the user goes to either view jobs or posted jobs page. (Make sure there is atleast one job posted to be able to reproduce this error). Screenshot of error is attached:

![Screenshot from 2024-10-21 18-02-28](https://github.com/user-attachments/assets/585193d8-9856-4901-a661-ee363c3fd46f)

**Comment by ubaidrmn** [comment]
I have fixed this issue in PR#13 [https://github.com/Devmangrani/JobSewa/pull/13](url)

**Comment by Devmangrani** [comment]
This is a good issue you’re working on, @ubaidrmn  Go ahead and make the changes, and I look forward to seeing your fix in #13. Happy contributing!
