### ISSUE TITLE
Some UI/UX issues

### ISSUE THREAD

**Issue by ashisvi** [Devmangrani/JobSewa#19]
# Issues in UI/UX as per my knowledge.

1. [Available Jobs](https://job-sewa.vercel.app/frontend/displayJobs) should have search option.
2. Job cards have different height.

![image](https://github.com/user-attachments/assets/83d0c5ae-3dd2-4a94-9842-0db4858436c7)

3. Mouse cursor should only hand on clickable button and links, not on whole card.

![image](https://github.com/user-attachments/assets/e921205a-ae04-46dd-82a2-7d9cdbc156fa)

4. The content of home page goes a little bit out side of background.

![image](https://github.com/user-attachments/assets/c294ab9d-a408-446e-a3ad-eaf218576490)

I want to fix this issue @Devmangrani.

**Comment by Devmangrani** [comment]
Thank you, @ashisvi  for pointing out these UI/UX issues! I appreciate your attention to detail. Please go ahead and work on fixing them, and feel free to reach out if you need anything. Looking forward to your contributions!
