### ISSUE TITLE
UI Issue: Cards are of different sizes

### ISSUE THREAD

**Issue by Aarushibhatia12** [Devmangrani/JobSewa#20]
In the organisations section, the cards are of different sizes. But as the description length is different for all cards, a read more toggle will be needed. Also added some padding to make it look neat. Please check, if you find it helpful then please assign me the task under hacktoberfest.

from this: 
![image](https://github.com/user-attachments/assets/84ecbf4d-d399-48a3-9fd1-506bab18c2b7)

to this: 
![Screenshot 2024-10-21 214322](https://github.com/user-attachments/assets/c2a6d257-dbae-4893-9e07-bea0380f2c05)

**Comment by Devmangrani** [comment]
Go for it, @Aarushibhatia12  This improvement sounds great, and I’ve assigned you the task under Hacktoberfest. 
Keep contributing!
