### ISSUE TITLE
Enhancement Proposal: Highlight Current Tab in Navbar

### ISSUE THREAD

**Issue by Aarushibhatia12** [Devmangrani/JobSewa#22]
This issue proposes an enhancement to the navbar by implementing a highlight effect for the currently active tab. This will improve user navigation and provide a clearer indication of the user's current location within the application.

Current Behavior:
1. The navbar does not visually indicate which tab is currently active.
2. Users may find it difficult to determine their current section.

Proposed Changes:
1. Implement a highlight effect for the active tab in the navbar.
2. Ensure that the highlight effect is consistent across all tabs.

Benefits:
Improves user experience by providing clear navigation feedback.
Helps users easily identify their current section within the application.

please assign me this issue under hacktoberfest tag :)

**Comment by Devmangrani** [comment]
I've assigned you the issue under the Hacktoberfest tag! Keep contributing, and if you think of any more improvements, feel free to go for it!
