### ISSUE TITLE
Responsivness issue

### ISSUE THREAD

**Issue by Sumit1911** [Devmangrani/JobSewa#25]
there is an issue with small screen, the humbermenu already the clicked.
![image](https://github.com/user-attachments/assets/3090669e-5a13-46f0-873b-75f1ae27cb85)

please assign this issue with hactoberfest label

**Comment by Devmangrani** [comment]
Thank you for pointing this out. I've assigned the issue to you with the Hacktoberfest label. Looking forward to your contribution!
