### ISSUE TITLE
UI Enhancement: Increase title size

### ISSUE THREAD

**Issue by Aarushibhatia12** [Devmangrani/JobSewa#27]
Issue Description:

In the navbar, the project title appears smaller compared to the tabs. As the name of the project, it should be more prominent to enhance its visibility and significance.

It will look like this:

![image](https://github.com/user-attachments/assets/a67a2392-ca90-4b52-8b44-d1b917d74a52)

please assign this issue under hacktoberfest

**Comment by Devmangrani** [comment]
Thanks for the suggestion! I've assigned the issue to you under Hacktoberfest. Looking forward to your contribution!
