### ISSUE TITLE
Organization Page UI/UX

### ISSUE THREAD

**Issue by KhushiParekh** [Devmangrani/JobSewa#3]
## 📝 Description
The card size should remain constant regardless of the content inside it. Additionally, the hover color of the button needs to be updated to a different shade for better visual feedback.

### 📷 Screenshot or Visual Reference (optional)
<img width="1433" alt="Screenshot 2024-10-21 at 3 18 48 PM" src="https://github.com/user-attachments/assets/195323a9-8eea-4248-bb21-83263cd26724">

## 🐛 Bug Report (if applicable)

- **Steps to Reproduce:** 
  1. Add content to the card of varying lengths.
  2. Hover over the button to observe the color.
  3. Observe how the card size or button color behaves.
- **Expected behavior:** The card size remains fixed irrespective of the content length.
- **Actual behavior:** The card size fluctuates based on the content length.

## 💡 Enhancement / Feature Request (if applicable)
It would be beneficial to ensure that the card maintains a uniform size for a consistent layout. Also, changing the hover color of the button will improve user interaction feedback and overall UX.

**Comment by Devmangrani** [comment]
This is a great suggestion, and ensuring the card size remains fixed will definitely improve the layout consistency. Adjusting the hover color for better visual feedback is also a smart enhancement for user interaction. Go ahead with the changes, and feel free to keep contributing—your efforts are valuable to the project!

Keep up the great work! 🚀

**Comment by KhushiParekh** [comment]
<img width="1440" alt="Screenshot 2024-10-23 at 12 20 31 AM" src="https://github.com/user-attachments/assets/76edb30b-775c-4847-9a4c-02deebad0c2a">
?

**Comment by Devmangrani** [comment]
Yes, This is looks great
Go ahead with the changes, and feel free to keep contributing

**Comment by KhushiParekh** [comment]
retained the animation and also modified the layout for more professional look
<img width="1440" alt="Screenshot 2024-10-24 at 10 32 07 AM" src="https://github.com/user-attachments/assets/a29abf1d-ac6c-4ad9-bd04-14efb5a360ed">

does this work?

**Comment by Devmangrani** [comment]
Yess this will Work
In your given image, it shows that you have changed the layout and added animation, but in your PR, it’s not reflecting those changes. Could you please check and ensure that the layout and animation modifications are included in the PR as well?

**Comment by KhushiParekh** [comment]
yup ill raise the pr again
