### ISSUE TITLE
code of conduction.md

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [Devmangrani/JobSewa#34]
as its an open source so might be we need an code of conduct file

**Comment by RonakSurana-2001** [comment]
Can I contribute

**Comment by Devmangrani** [comment]
Hey @Mukesh-ghildiyal  and @RonakSurana-2001 

Go ahead, both of you can contribute to this issue. If you think any more improvements can be made, feel free to go for it. Keep up the great work, and happy contributing!
