### ISSUE TITLE
[BUG] : Negative Numbers in Job Posting Form & Past Deadlines Can Be Selected

### ISSUE THREAD

**Issue by ashish-um** [Devmangrani/JobSewa#48]
There is an issue with the job posting form where users can input negative numbers in "Salary" and "Number of Vacancies"  fields. Additionally, users can select a job deadline that is in the past, which should not be allowed.

https://github.com/user-attachments/assets/71ddf296-3a9e-422e-9f33-cf7a173e2dd0

@Devmangrani if this seems like a valid enhancement, I would like to work in this issue :)
**_Also please add gssoc-ext and hacktoberfest labels on it_**

**Comment by Devmangrani** [comment]
Hi @Picodes10,

You’ve chosen and identified a really good issue in the project! Keep it up, and feel free to get creative with your solution. Keep contributing, and great work so far!
