### ISSUE TITLE
Improving footer section for more interactivity

### ISSUE THREAD

**Issue by Sushil010** [Devmangrani/JobSewa#49]
Hey @Devmangrani I think the footer section still needs a little bit of revamp. 
![image](https://github.com/user-attachments/assets/6b1a94b4-6082-460d-b75e-20f1d675712e)

Instead of those boring text links I think some icons with some animated effect would be better. The design is ready will open a PR if you are okay and as soon as you assign me that.

**Comment by Devmangrani** [comment]
Hi @Sushil010 

That sounds like a great idea! I'm ready to merge the PR once you make those improvements. Feel free to go ahead and implement the changes! Looking forward to seeing it. Keep up the great work!
