### ISSUE TITLE
Homepage responsiveness optimization

### ISSUE THREAD

**Issue by sarwar-jahin-port** [Devmangrani/JobSewa#5]
### Now, the homepage is not properly responsive.
- I want to make the search section a single-line
- Also fix the alignment of the suggestion tags.

![image](https://github.com/user-attachments/assets/c4cc3250-d7fe-4359-aecd-3820ca1a1983)
@Devmangrani

**Comment by Devmangrani** [comment]
To make the homepage fully responsive, we can ensure the search section becomes a single line for better usability. I'll also work on fixing the alignment of the suggestion tags for a cleaner, more polished look. Feel free to share the image for more context if needed. Let’s get these improvements done!

Keep up the good work!

**Comment by Devmangrani** [comment]
I’ve seen your PR—great work! If you think of any additional changes to make the project more user-friendly and useful for the community, feel free to go ahead. Keep it up!
