### ISSUE TITLE
Navbar UI improvement 

### ISSUE THREAD

**Issue by KhushiParekh** [Devmangrani/JobSewa#58]
have improved the ui of the navbar for better user experience 

<img width="1438" alt="Screenshot 2024-10-24 at 12 27 07 PM" src="https://github.com/user-attachments/assets/a0fbf55b-0d22-46e9-9275-6139724d9d56">

<img width="1440" alt="Screenshot 2024-10-24 at 12 27 24 PM" src="https://github.com/user-attachments/assets/34feb1a0-a604-407b-8325-39545f5c21be">

assign me the task so i can take it forward

**Comment by Devmangrani** [comment]
It is now looking great! Great work done! If you think any more changes can be made, go for it.
Keep contributing.

**Comment by KhushiParekh** [comment]
have raised the pr

**Comment by Devmangrani** [comment]
I have merged your PR. Thanks a lot for your contribution, @KhushiParekh  
If you feel there are any more changes that could enhance the experience further, feel free to go for it. 
Keep contributing and great work so far!
