### ISSUE TITLE
Organizations card size responsiveness

### ISSUE THREAD

**Issue by sarwar-jahin-port** [Devmangrani/JobSewa#6]
### Organizations card size is taking unnecessary space on mobile view
- The government tag and more details button could be in one line.

![image](https://github.com/user-attachments/assets/d959a48d-b63c-4868-960a-f01cb4e5c574)
@Devmangrani

**Comment by Devmangrani** [comment]
Go ahead and make the adjustments, happy contributing!

**Comment by sarwar-jahin-port** [comment]
I made a PR. Please review and let me know if any changes are required. 
If you have a specific issue that needs to be fixed or any feature you want. Please feel free to ask me. I will be glad to contribute more. @Devmangrani

**Comment by Devmangrani** [comment]
Thank you, @sarwar-jahin-port  If you think the UI can be improved, please go ahead and enhance the UI/UX for the project. Your contributions are much appreciated!
