### ISSUE TITLE
Clicking on the "Posted jobs" button abruptly leads to the login page.

### ISSUE THREAD

**Issue by Blink-drift** [Devmangrani/JobSewa#66]
**Solution**

An intermediary page that notifies the user to first login in order to be able to access the sections.

**Comment by Blink-drift** [comment]
Could you please assign this Issue to me?

**Comment by Devmangrani** [comment]
Hi @Blink-drift 

You've identified a great improvement—thanks for that! Instead of creating an intermediary page, you could consider adding a notification prompt to encourage users to log in. Feel free to implement it as you think best, and keep up the good work! 😊

**Comment by Blink-drift** [comment]
Thank you for assigning me, yes, that's a better idea, I will try doing that
