### ISSUE TITLE
Better UI page for Enter job details

### ISSUE THREAD

**Issue by Chelseasingla1** [Devmangrani/JobSewa#7]
Screenshot:

<img width="685" alt="Screenshot 2024-10-21 at 4 47 50 PM" src="https://github.com/user-attachments/assets/375a6784-619d-4e0f-aecf-da114d4d6469">
<img width="688" alt="Screenshot 2024-10-21 at 4 47 44 PM" src="https://github.com/user-attachments/assets/1e02d09d-9ec5-42c3-8721-a6f1b972e475">

I would like to make this UI a little better.

**Comment by Chelseasingla1** [comment]
Please assign me this issue @Devmangrani

**Comment by Devmangrani** [comment]
Sounds great! I've assigned you the issue—looking forward to seeing your improvements. Happy contributing!
