### ISSUE TITLE
[FEATURE] Missing Navigation Elements on Login/Signup Page

### ISSUE THREAD

**Issue by Devmangrani** [Devmangrani/JobSewa#71]
# Missing Navigation Elements on Login/Signup Page

## Current Behavior
The login/signup page currently lacks essential navigation elements:
- No logo/home button present
- Missing "Back" or "Return to Home" navigation option
- Users have no clear way to exit the authentication flow without using browser navigation

## Expected Behavior
- Company/Project logo should be present and clickable to return to home page
- Clear navigation option to return to the main page should be available
- Users should be able to easily navigate away from the auth flow if needed

## Impact
- Decreased user experience
- Violates web accessibility guidelines
- Forces users to rely on browser back button
- May increase user frustration and bounce rates

## Proposed Solution
1. Add clickable logo in the top-left corner
2. Implement "Back to Home" link with appropriate styling
3. Ensure all new navigation elements are keyboard-accessible
4. Maintain consistent styling with existing UI

**Comment by piyush-gangrade** [comment]
@Devmangrani, Could you please assign this to me under Hacktoberfest?

**Comment by Devmangrani** [comment]
Hi! @piyush-gangrade 

Yes, I have Assigned you this issue. Go ahead, and thank you for stepping in!

**Comment by piyush-gangrade** [comment]
@Devmangrani, please check which design you prefer and let me know if you want any changes.

*Design 1*
![Group 2](https://github.com/user-attachments/assets/ffbb0f87-c5fe-4482-8518-6d97c5ede1c1)

*Design 2*
![Group 3](https://github.com/user-attachments/assets/fdfece4d-bbe5-48cf-9800-2d62fd3f19d0)

**Comment by Devmangrani** [comment]
Hi @piyush-gangrade 

Both designs look fantastic, but I'm leaning toward the second one—it really aligns well with the style we're aiming for. Great work! Let me know if there are any updates or if you need further feedback!

**Comment by piyush-gangrade** [comment]
@Devmangrani, could you please close this issue

**Comment by Devmangrani** [comment]
Yaa , Sure
