### ISSUE TITLE
[BUG]: Page title overlapping with navabar while searching

### ISSUE THREAD

**Issue by Sushil010** [Devmangrani/JobSewa#80]
When searching for some job the search result pops and and main page gets overlapped with navbar

Go to search bar
Type on any job 
Click on search option

An appropriate margin should be between navbar and main page content making proper user redability.

![image](https://github.com/user-attachments/assets/f955eafa-245b-42dc-8db6-e8f7232167ba)

**Comment by Sushil010** [comment]
@Devmangrani can you check if it is behaving as expected and will be happy to solve if any issue still exists
.

**Comment by Devmangrani** [comment]
I’ve seen your work, and it’s truly impressive! Thank you for your dedication to refining our homepage—you’ve consistently tackled several key issues and done it in such a thoughtful, user-focused way. Really grateful for your contributions; they’re making a big difference!

**Comment by Sushil010** [comment]
Thanks @Devmangrani for your feedback, was busy on some personal work. Will continue to solve remaining issues keep on providing feedback as it will be helpful to improve my personal experience too.

**Comment by Devmangrani** [comment]
No problem at all, @Sushil010 
Your willingness to tackle the remaining issues is greatly appreciated, and I’m here to provide any feedback you need. It’s great to see your growth through this process, and I’m excited to see what we can accomplish together!
