### ISSUE TITLE
[BUG] forget password not working properly

### ISSUE THREAD

**Issue by piyush-gangrade** [Devmangrani/JobSewa#84]
**Describe the bug**
forget password function doesn't work properly.

**To Reproduce**
1. Go to forget password page
2. Fill all details
3. Click on reset password

**Expected behavior**
The account password should be reset properly.

**Screenshots**
![Screenshot 2024-10-28 224330](https://github.com/user-attachments/assets/9ab6b302-cf24-4158-9a99-676493660a17)

**Comment by piyush-gangrade** [comment]
@Devmangrani, I can fix this bug. Please assign this to me.

**Comment by Devmangrani** [comment]
Absolutely, @piyush-gangrade 
Go ahead—great choice on addressing this issue. Thank you for taking it up!
