### ISSUE TITLE
Fixing the alignment of searchbar on available job page

### ISSUE THREAD

**Issue by AayushhGoyal** [Devmangrani/JobSewa#87]
the searchbar in available job page isn't positioned correctly

![image](https://github.com/user-attachments/assets/4ba5edcc-a903-4645-bf8d-63c5e52dc075)

**Comment by AayushhGoyal** [comment]
@Devmangrani please assign this to me i can work upon it

**Comment by Devmangrani** [comment]
Thank you for taking on this alignment fix, @AayushhGoyal  Appreciate your attention to detail in enhancing the UI. Looking forward to seeing the improved search bar layout!
