### ISSUE TITLE
Make JobSewa button working

### ISSUE THREAD

**Issue by KhanjarSingh** [Devmangrani/JobSewa#9]
<img width="211" alt="Screenshot 2024-10-21 at 5 16 04 PM" src="https://github.com/user-attachments/assets/c358cf8b-0f56-4606-b293-c1b97a2abbb1">
Here when we click the Main button it would be bteer if it redirects us to home website

**Comment by KhanjarSingh** [comment]
@Devmangrani i would like to work on this under the hacktoberfest tah

**Comment by Devmangrani** [comment]
Thanks for your interest, @KhanjarSingh! I've assigned you the issue under the Hacktoberfest tag. Looking forward to your contribution!

**Comment by KhanjarSingh** [comment]
@Devmangrani I have made changes please check and give hacktober tag :)
